### ISSUE TITLE
Requiring text along side embed

### ISSUE THREAD

**Issue by crazychris2404** [jlnpinheiro/discord-webhook-client#5]
Would it be possible to use this without having to send text alongside the embed message. As leaving blank throws a error

**Comment by jlnpinheiro** [comment]
@crazychris2404 you can send a simple message without anyone embeds.

**Comment by crazychris2404** [comment]
Is it possible to have embeds without the simple text?

**Comment by jlnpinheiro** [comment]
> Would it be possible to use this without having to send text alongside the embed message. As leaving blank throws a error

@crazychris2404 you can send messsges with embeds without title or description. The only limitation is the max number of embeds per message is 10.

**Comment by crazychris2404** [comment]
I cannot send a embed without having any text for this part 
![image](https://user-images.githubusercontent.com/36340714/126561074-6d58f4c6-652e-4b84-bbdf-322df4cfcb46.png)

**Comment by jlnpinheiro** [comment]
@crazychris2404 When you try to send a message without embeds whats happening? An exception was throw?

**Comment by crazychris2404** [comment]
Yes the follow exception is thrown, ```The message param is invalid: The "content" element cannot be null or empty.```

**Comment by crazychris2404** [comment]
@jlnpinheiro

**Comment by jlnpinheiro** [comment]
> I cannot send a embed without having any text for this part 
> ![image](https://user-images.githubusercontent.com/36340714/126561074-6d58f4c6-652e-4b84-bbdf-322df4cfcb46.png)
> 

@crazychris2404 the "content" cannot be null becase this is a principal text of a message. Without a content and no embed  the message wouldn't say anything!

**Comment by crazychris2404** [comment]
@jlnpinheiro I want a embed without text above so it has a layout similar to this 
![image](https://user-images.githubusercontent.com/36340714/126641012-a428b3d4-865c-4048-8145-0a28e38c63b9.png)

**Comment by jlnpinheiro** [comment]
> @jlnpinheiro I want a embed without text above so it has a layout similar to this 
> ![image](https://user-images.githubusercontent.com/36340714/126641012-a428b3d4-865c-4048-8145-0a28e38c63b9.png)
> 

@crazychris2404 please send me a pull request changing content with not required. Ok?

**Comment by cxnky** [comment]
@jlnpinheiro i've put a pr through for this.

**Comment by crazychris2404** [comment]
Can you inform me once a release is made using this PR please @jlnpinheiro

**Comment by jlnpinheiro** [comment]
> Can you inform me once a release is made using this PR please @jlnpinheiro 

@crazychris2404 I haven't created the release yet.  When I create I will let you know.

**Comment by jlnpinheiro** [comment]
@crazychris2404 @cxnky the release 3.1.0 is avaible! Tks for PR @cxnky ! 👍👊
